module.exports = {
  projects: [
    '<rootDir>/apps/todos',
    '<rootDir>/apps/api',
    '<rootDir>/libs/data',
    '<rootDir>/libs/ui',
    '<rootDir>/apps/ng-app',
    '<rootDir>/libs/ng/lib0',
    '<rootDir>/libs/ng/shared-utils',
    '<rootDir>/libs/shared-utils',
    '<rootDir>/libs/ng/lib1',
    '<rootDir>/libs/ng/lib2',
    '<rootDir>/libs/ng/lib3',
    '<rootDir>/libs/ng/lib4',
    '<rootDir>/libs/ng/lib5',
    '<rootDir>/libs/ng/lib6',
    '<rootDir>/libs/ng/lib7',
    '<rootDir>/libs/ng/lib8',
    '<rootDir>/libs/ng/lib10',
    '<rootDir>/libs/ng/lib11',
    '<rootDir>/libs/ng/lib12',
    '<rootDir>/libs/ng/lib13',
    '<rootDir>/libs/ng/lib14',
    '<rootDir>/libs/ng/lib9',
  ],
};
